/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgCharts: typeof import('./src/components/agCharts.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
